### ISSUE TITLE
Protocol implementation

### ISSUE THREAD

**Issue by rom1504** [oldmanmike/opensandbox#1]
For your protocol implementation, you might be interested by [protocol.json](https://github.com/PrismarineJS/minecraft-data/blob/master/data/1.8/protocol.json). The purpose of that file is defining the protocol declaratively so projects in various languages can use it and the maintenance can be shared. There's some (automatically generated) [doc](http://prismarinejs.github.io/minecraft-data/?d=protocol) about it.

Since it's haskell and you probably want to have a type for every packet, it might mean generating these type from that file. Or maybe some other way. I learned haskell but I don't have too much experience with it, and I'd be interested to know what you think about this.

Just for information, protocol.json is currently [used](https://github.com/PrismarineJS/node-minecraft-protocol) directly (dynamically) in node.js, there's a java class [generator](https://github.com/Johni0702/ProtocolGen) from it, and it is planned to use it in a python [project](https://github.com/SpockBotMC/SpockBot).

Anyway, implementing the protocol in haskell should be interesting. I'll be following that :)

**Comment by oldmanmike** [comment]
Interesting, I grabbed the json and generated the types and Aeson instances for them, but it's not the definitions I need and I'm not sure how much work I'd have to do to adapt what I'm getting for free into what I actually want. I'll play around with it and see what I can dig up on Hackage, it's great to know that these resources exist. Not sure how much mileage I'll be able to get out of this with a strong statically typed language, but I'm bookmarking that repo nonetheless.
